### ISSUE TITLE
Tincd -n <network-name> -K <encryption-standard> throwing tincd: invalid option -- 'K'

### ISSUE THREAD

**Issue by NDGNUITY** [azrdev/tinc1.1pre-fedora#1]
Hi trying this on CentOS 7 but keep getting the message "tincd: invalid option -- 'K'. I've looked at the man pages and other pages to see what the problem could be, any insights?

**Comment by azrdev** [comment]
@JX-I looks to me like you confused `tincd` (the daemon executable) with `tinc` (the tool to interact with a running daemon). However, I don't see the `-K` option in neither manpage, where did you get it from?

**Comment by NDGNUITY** [comment]
To create the keys for the network this is the command that's listed in virtually every tutorial-> tincd -n "network" -k4092 or something like that, with the 4092 being the level of encryption. After I left this message, I installed the 1.0... version of Tinc from epel and the above command ran without issue.

**Comment by azrdev** [comment]
@JX-I quoting from #tinc @ hackint irc:

> 15:40 <azrdev> anyways, neither one has -K here (on cli, in --help or manpage)
15:53 <aiyion> -K was active in tinc1.0
15:53 <aiyion> see https://www.tinc-vpn.org/documentation/tincd.8
15:54 <aiyion> under 1.1 its --generate-keys
15:54 <aiyion> however I dont recall a need to use it in the setup
15:54 <aiyion> it probably had a sane default

> 15:55 <aiyion> It got pretty comfortable using the init parameter of tinc.

> 19:47 <guus> With tinc 1.1 you have to use "tinc -n <netname> generate-keys", or rather you'd create all initial configuration in one go with "tinc -n <netname> init"
